/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.net.URI;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for Links
 */
public class LinksTest {
    private final Links model = new Links();

    /**
     * Model tests for Links
     */
    @Test
    public void testLinks() {
        // TODO: test Links
    }

    /**
     * Test the property 'self'
     */
    @Test
    public void selfTest() {
        // TODO: test self
    }

    /**
     * Test the property 'first'
     */
    @Test
    public void firstTest() {
        // TODO: test first
    }

    /**
     * Test the property 'prev'
     */
    @Test
    public void prevTest() {
        // TODO: test prev
    }

    /**
     * Test the property 'next'
     */
    @Test
    public void nextTest() {
        // TODO: test next
    }

    /**
     * Test the property 'last'
     */
    @Test
    public void lastTest() {
        // TODO: test last
    }

}
