/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBAccount6DetailAccountInner;
import com.konfigthis.client.model.OBAccountStatus1Code;
import com.konfigthis.client.model.OBBranchAndFinancialInstitutionIdentification50;
import com.konfigthis.client.model.OBExternalAccountSubType1Code;
import com.konfigthis.client.model.OBExternalAccountType1Code;
import com.konfigthis.client.model.OBExternalSwitchStatusCode;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBAccount6Detail
 */
public class OBAccount6DetailTest {
    private final OBAccount6Detail model = new OBAccount6Detail();

    /**
     * Model tests for OBAccount6Detail
     */
    @Test
    public void testOBAccount6Detail() {
        // TODO: test OBAccount6Detail
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusUpdateDateTime'
     */
    @Test
    public void statusUpdateDateTimeTest() {
        // TODO: test statusUpdateDateTime
    }

    /**
     * Test the property 'currency'
     */
    @Test
    public void currencyTest() {
        // TODO: test currency
    }

    /**
     * Test the property 'accountType'
     */
    @Test
    public void accountTypeTest() {
        // TODO: test accountType
    }

    /**
     * Test the property 'accountSubType'
     */
    @Test
    public void accountSubTypeTest() {
        // TODO: test accountSubType
    }

    /**
     * Test the property 'description'
     */
    @Test
    public void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'nickname'
     */
    @Test
    public void nicknameTest() {
        // TODO: test nickname
    }

    /**
     * Test the property 'openingDate'
     */
    @Test
    public void openingDateTest() {
        // TODO: test openingDate
    }

    /**
     * Test the property 'maturityDate'
     */
    @Test
    public void maturityDateTest() {
        // TODO: test maturityDate
    }

    /**
     * Test the property 'switchStatus'
     */
    @Test
    public void switchStatusTest() {
        // TODO: test switchStatus
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'servicer'
     */
    @Test
    public void servicerTest() {
        // TODO: test servicer
    }

}
