/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBExternalAccountRole1Code;
import com.konfigthis.client.model.OBExternalLegalStructureType1Code;
import com.konfigthis.client.model.OBExternalPartyType1Code;
import com.konfigthis.client.model.OBParty2AddressInner;
import com.konfigthis.client.model.OBPartyRelationships1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBParty2
 */
public class OBParty2Test {
    private final OBParty2 model = new OBParty2();

    /**
     * Model tests for OBParty2
     */
    @Test
    public void testOBParty2() {
        // TODO: test OBParty2
    }

    /**
     * Test the property 'partyId'
     */
    @Test
    public void partyIdTest() {
        // TODO: test partyId
    }

    /**
     * Test the property 'partyNumber'
     */
    @Test
    public void partyNumberTest() {
        // TODO: test partyNumber
    }

    /**
     * Test the property 'partyType'
     */
    @Test
    public void partyTypeTest() {
        // TODO: test partyType
    }

    /**
     * Test the property 'name'
     */
    @Test
    public void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'fullLegalName'
     */
    @Test
    public void fullLegalNameTest() {
        // TODO: test fullLegalName
    }

    /**
     * Test the property 'legalStructure'
     */
    @Test
    public void legalStructureTest() {
        // TODO: test legalStructure
    }

    /**
     * Test the property 'beneficialOwnership'
     */
    @Test
    public void beneficialOwnershipTest() {
        // TODO: test beneficialOwnership
    }

    /**
     * Test the property 'accountRole'
     */
    @Test
    public void accountRoleTest() {
        // TODO: test accountRole
    }

    /**
     * Test the property 'emailAddress'
     */
    @Test
    public void emailAddressTest() {
        // TODO: test emailAddress
    }

    /**
     * Test the property 'phone'
     */
    @Test
    public void phoneTest() {
        // TODO: test phone
    }

    /**
     * Test the property 'mobile'
     */
    @Test
    public void mobileTest() {
        // TODO: test mobile
    }

    /**
     * Test the property 'relationships'
     */
    @Test
    public void relationshipsTest() {
        // TODO: test relationships
    }

    /**
     * Test the property 'address'
     */
    @Test
    public void addressTest() {
        // TODO: test address
    }

}
