/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBInterestCalculationMethod1Code;
import com.konfigthis.client.model.OBOtherCodeType10;
import com.konfigthis.client.model.OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInner;
import com.konfigthis.client.model.OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerLoanInterestTierBandInnerLoanInterestFeesChargesInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner
 */
public class OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInnerTest {
    private final OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner model = new OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner();

    /**
     * Model tests for OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner
     */
    @Test
    public void testOBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner() {
        // TODO: test OBReadProduct2DataProductInnerOtherProductTypeLoanInterestLoanInterestTierBandSetInner
    }

    /**
     * Test the property 'tierBandMethod'
     */
    @Test
    public void tierBandMethodTest() {
        // TODO: test tierBandMethod
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'calculationMethod'
     */
    @Test
    public void calculationMethodTest() {
        // TODO: test calculationMethod
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherCalculationMethod'
     */
    @Test
    public void otherCalculationMethodTest() {
        // TODO: test otherCalculationMethod
    }

    /**
     * Test the property 'loanInterestTierBand'
     */
    @Test
    public void loanInterestTierBandTest() {
        // TODO: test loanInterestTierBand
    }

    /**
     * Test the property 'loanInterestFeesCharges'
     */
    @Test
    public void loanInterestFeesChargesTest() {
        // TODO: test loanInterestFeesCharges
    }

}
