/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBReadConsentResponse1Data
 */
public class OBReadConsentResponse1DataTest {
    private final OBReadConsentResponse1Data model = new OBReadConsentResponse1Data();

    /**
     * Model tests for OBReadConsentResponse1Data
     */
    @Test
    public void testOBReadConsentResponse1Data() {
        // TODO: test OBReadConsentResponse1Data
    }

    /**
     * Test the property 'consentId'
     */
    @Test
    public void consentIdTest() {
        // TODO: test consentId
    }

    /**
     * Test the property 'creationDateTime'
     */
    @Test
    public void creationDateTimeTest() {
        // TODO: test creationDateTime
    }

    /**
     * Test the property 'status'
     */
    @Test
    public void statusTest() {
        // TODO: test status
    }

    /**
     * Test the property 'statusUpdateDateTime'
     */
    @Test
    public void statusUpdateDateTimeTest() {
        // TODO: test statusUpdateDateTime
    }

    /**
     * Test the property 'permissions'
     */
    @Test
    public void permissionsTest() {
        // TODO: test permissions
    }

    /**
     * Test the property 'expirationDateTime'
     */
    @Test
    public void expirationDateTimeTest() {
        // TODO: test expirationDateTime
    }

    /**
     * Test the property 'transactionFromDateTime'
     */
    @Test
    public void transactionFromDateTimeTest() {
        // TODO: test transactionFromDateTime
    }

    /**
     * Test the property 'transactionToDateTime'
     */
    @Test
    public void transactionToDateTimeTest() {
        // TODO: test transactionToDateTime
    }

}
