/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBFeeFrequency1Code2;
import com.konfigthis.client.model.OBFeeFrequency1Code3;
import com.konfigthis.client.model.OBFeeType1Code;
import com.konfigthis.client.model.OBInterestRateType1Code1;
import com.konfigthis.client.model.OBOtherCodeType16;
import com.konfigthis.client.model.OBOtherCodeType17;
import com.konfigthis.client.model.OBOtherCodeType18;
import com.konfigthis.client.model.OBOtherFeeChargeDetailType;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
 */
public class OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInnerTest {
    private final OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner model = new OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner();

    /**
     * Model tests for OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
     */
    @Test
    public void testOBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner() {
        // TODO: test OBReadProduct2DataProductInnerOtherProductTypeRepaymentRepaymentFeeChargesRepaymentFeeChargeDetailInner
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'negotiableIndicator'
     */
    @Test
    public void negotiableIndicatorTest() {
        // TODO: test negotiableIndicator
    }

    /**
     * Test the property 'feeAmount'
     */
    @Test
    public void feeAmountTest() {
        // TODO: test feeAmount
    }

    /**
     * Test the property 'feeRate'
     */
    @Test
    public void feeRateTest() {
        // TODO: test feeRate
    }

    /**
     * Test the property 'feeRateType'
     */
    @Test
    public void feeRateTypeTest() {
        // TODO: test feeRateType
    }

    /**
     * Test the property 'applicationFrequency'
     */
    @Test
    public void applicationFrequencyTest() {
        // TODO: test applicationFrequency
    }

    /**
     * Test the property 'calculationFrequency'
     */
    @Test
    public void calculationFrequencyTest() {
        // TODO: test calculationFrequency
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherFeeType'
     */
    @Test
    public void otherFeeTypeTest() {
        // TODO: test otherFeeType
    }

    /**
     * Test the property 'otherFeeRateType'
     */
    @Test
    public void otherFeeRateTypeTest() {
        // TODO: test otherFeeRateType
    }

    /**
     * Test the property 'otherApplicationFrequency'
     */
    @Test
    public void otherApplicationFrequencyTest() {
        // TODO: test otherApplicationFrequency
    }

    /**
     * Test the property 'otherCalculationFrequency'
     */
    @Test
    public void otherCalculationFrequencyTest() {
        // TODO: test otherCalculationFrequency
    }

}
