/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount11;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount2;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount3;
import com.konfigthis.client.model.OBActiveOrHistoricCurrencyAndAmount4;
import com.konfigthis.client.model.OBExternalStandingOrderStatus1Code;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.HashMap;
import java.util.Map;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBStandingOrder6Basic
 */
public class OBStandingOrder6BasicTest {
    private final OBStandingOrder6Basic model = new OBStandingOrder6Basic();

    /**
     * Model tests for OBStandingOrder6Basic
     */
    @Test
    public void testOBStandingOrder6Basic() {
        // TODO: test OBStandingOrder6Basic
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'standingOrderId'
     */
    @Test
    public void standingOrderIdTest() {
        // TODO: test standingOrderId
    }

    /**
     * Test the property 'frequency'
     */
    @Test
    public void frequencyTest() {
        // TODO: test frequency
    }

    /**
     * Test the property 'reference'
     */
    @Test
    public void referenceTest() {
        // TODO: test reference
    }

    /**
     * Test the property 'firstPaymentDateTime'
     */
    @Test
    public void firstPaymentDateTimeTest() {
        // TODO: test firstPaymentDateTime
    }

    /**
     * Test the property 'nextPaymentDateTime'
     */
    @Test
    public void nextPaymentDateTimeTest() {
        // TODO: test nextPaymentDateTime
    }

    /**
     * Test the property 'lastPaymentDateTime'
     */
    @Test
    public void lastPaymentDateTimeTest() {
        // TODO: test lastPaymentDateTime
    }

    /**
     * Test the property 'finalPaymentDateTime'
     */
    @Test
    public void finalPaymentDateTimeTest() {
        // TODO: test finalPaymentDateTime
    }

    /**
     * Test the property 'numberOfPayments'
     */
    @Test
    public void numberOfPaymentsTest() {
        // TODO: test numberOfPayments
    }

    /**
     * Test the property 'standingOrderStatusCode'
     */
    @Test
    public void standingOrderStatusCodeTest() {
        // TODO: test standingOrderStatusCode
    }

    /**
     * Test the property 'firstPaymentAmount'
     */
    @Test
    public void firstPaymentAmountTest() {
        // TODO: test firstPaymentAmount
    }

    /**
     * Test the property 'nextPaymentAmount'
     */
    @Test
    public void nextPaymentAmountTest() {
        // TODO: test nextPaymentAmount
    }

    /**
     * Test the property 'lastPaymentAmount'
     */
    @Test
    public void lastPaymentAmountTest() {
        // TODO: test lastPaymentAmount
    }

    /**
     * Test the property 'finalPaymentAmount'
     */
    @Test
    public void finalPaymentAmountTest() {
        // TODO: test finalPaymentAmount
    }

    /**
     * Test the property 'supplementaryData'
     */
    @Test
    public void supplementaryDataTest() {
        // TODO: test supplementaryData
    }

}
