/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OBExternalStatementType1Code;
import com.konfigthis.client.model.OBStatement2StatementBenefitInner;
import com.konfigthis.client.model.OBStatement2StatementDateTimeInner;
import com.konfigthis.client.model.OBStatement2StatementFeeInner;
import com.konfigthis.client.model.OBStatement2StatementInterestInner;
import com.konfigthis.client.model.OBStatement2StatementRateInner;
import com.konfigthis.client.model.OBStatement2StatementValueInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OBStatement2Basic
 */
public class OBStatement2BasicTest {
    private final OBStatement2Basic model = new OBStatement2Basic();

    /**
     * Model tests for OBStatement2Basic
     */
    @Test
    public void testOBStatement2Basic() {
        // TODO: test OBStatement2Basic
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    public void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'statementId'
     */
    @Test
    public void statementIdTest() {
        // TODO: test statementId
    }

    /**
     * Test the property 'statementReference'
     */
    @Test
    public void statementReferenceTest() {
        // TODO: test statementReference
    }

    /**
     * Test the property 'type'
     */
    @Test
    public void typeTest() {
        // TODO: test type
    }

    /**
     * Test the property 'startDateTime'
     */
    @Test
    public void startDateTimeTest() {
        // TODO: test startDateTime
    }

    /**
     * Test the property 'endDateTime'
     */
    @Test
    public void endDateTimeTest() {
        // TODO: test endDateTime
    }

    /**
     * Test the property 'creationDateTime'
     */
    @Test
    public void creationDateTimeTest() {
        // TODO: test creationDateTime
    }

    /**
     * Test the property 'statementDescription'
     */
    @Test
    public void statementDescriptionTest() {
        // TODO: test statementDescription
    }

    /**
     * Test the property 'statementBenefit'
     */
    @Test
    public void statementBenefitTest() {
        // TODO: test statementBenefit
    }

    /**
     * Test the property 'statementFee'
     */
    @Test
    public void statementFeeTest() {
        // TODO: test statementFee
    }

    /**
     * Test the property 'statementInterest'
     */
    @Test
    public void statementInterestTest() {
        // TODO: test statementInterest
    }

    /**
     * Test the property 'statementDateTime'
     */
    @Test
    public void statementDateTimeTest() {
        // TODO: test statementDateTime
    }

    /**
     * Test the property 'statementRate'
     */
    @Test
    public void statementRateTest() {
        // TODO: test statementRate
    }

    /**
     * Test the property 'statementValue'
     */
    @Test
    public void statementValueTest() {
        // TODO: test statementValue
    }

}
