/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OtherFeeTypeProperty3Inner1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OverdraftFeeChargeCapPropertyInner4
 */
public class OverdraftFeeChargeCapPropertyInner4Test {
    private final OverdraftFeeChargeCapPropertyInner4 model = new OverdraftFeeChargeCapPropertyInner4();

    /**
     * Model tests for OverdraftFeeChargeCapPropertyInner4
     */
    @Test
    public void testOverdraftFeeChargeCapPropertyInner4() {
        // TODO: test OverdraftFeeChargeCapPropertyInner4
    }

    /**
     * Test the property 'feeType'
     */
    @Test
    public void feeTypeTest() {
        // TODO: test feeType
    }

    /**
     * Test the property 'overdraftControlIndicator'
     */
    @Test
    public void overdraftControlIndicatorTest() {
        // TODO: test overdraftControlIndicator
    }

    /**
     * Test the property 'minMaxType'
     */
    @Test
    public void minMaxTypeTest() {
        // TODO: test minMaxType
    }

    /**
     * Test the property 'feeCapOccurrence'
     */
    @Test
    public void feeCapOccurrenceTest() {
        // TODO: test feeCapOccurrence
    }

    /**
     * Test the property 'feeCapAmount'
     */
    @Test
    public void feeCapAmountTest() {
        // TODO: test feeCapAmount
    }

    /**
     * Test the property 'cappingPeriod'
     */
    @Test
    public void cappingPeriodTest() {
        // TODO: test cappingPeriod
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherFeeType'
     */
    @Test
    public void otherFeeTypeTest() {
        // TODO: test otherFeeType
    }

}
