/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OverdraftFeesChargesPropertyInner3;
import com.konfigthis.client.model.OverdraftTierBandPropertyInner1;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for OverdraftTierBandSetPropertyInner1
 */
public class OverdraftTierBandSetPropertyInner1Test {
    private final OverdraftTierBandSetPropertyInner1 model = new OverdraftTierBandSetPropertyInner1();

    /**
     * Model tests for OverdraftTierBandSetPropertyInner1
     */
    @Test
    public void testOverdraftTierBandSetPropertyInner1() {
        // TODO: test OverdraftTierBandSetPropertyInner1
    }

    /**
     * Test the property 'tierBandMethod'
     */
    @Test
    public void tierBandMethodTest() {
        // TODO: test tierBandMethod
    }

    /**
     * Test the property 'overdraftType'
     */
    @Test
    public void overdraftTypeTest() {
        // TODO: test overdraftType
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'authorisedIndicator'
     */
    @Test
    public void authorisedIndicatorTest() {
        // TODO: test authorisedIndicator
    }

    /**
     * Test the property 'bufferAmount'
     */
    @Test
    public void bufferAmountTest() {
        // TODO: test bufferAmount
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'overdraftTierBand'
     */
    @Test
    public void overdraftTierBandTest() {
        // TODO: test overdraftTierBand
    }

    /**
     * Test the property 'overdraftFeesCharges'
     */
    @Test
    public void overdraftFeesChargesTest() {
        // TODO: test overdraftFeesCharges
    }

}
