/*
 * Account Information API
 * In this document, you'll find the steps your organization needs to take to use our API services. Included in this guide are details of request and response messages used to support your organization’s integration. The intended audience for this document are **Technical Architects**, **Development Engineers**, **Test Engineers**, and **Operation & Maintenance Engineers** involved in development and support of your organization’s integration. Setting up our API Services is best completed with the assistance of your organization’s IT team, or someone with experience and knowledge of application programming interfaces. This should include experience with **JSON payloads**, **security** and **public key infrastructure (PKI)**. This Document describes the following request and response structure of HSBCnet - Account Information API. For detail implementation guidelines, please refer to the respective section from [develop.hsbc.com](https://develop.hsbc.com/ob-api-documentation/account-information-uk-personal-v319) 
 *
 * The version of the OpenAPI document: 3.1.11
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.OtherApplicationFrequencyProperty4;
import com.konfigthis.client.model.OtherBankInterestTypeProperty1;
import com.konfigthis.client.model.OtherCalculationFrequencyProperty4;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for TierBandPropertyInner1
 */
public class TierBandPropertyInner1Test {
    private final TierBandPropertyInner1 model = new TierBandPropertyInner1();

    /**
     * Model tests for TierBandPropertyInner1
     */
    @Test
    public void testTierBandPropertyInner1() {
        // TODO: test TierBandPropertyInner1
    }

    /**
     * Test the property 'identification'
     */
    @Test
    public void identificationTest() {
        // TODO: test identification
    }

    /**
     * Test the property 'tierValueMinimum'
     */
    @Test
    public void tierValueMinimumTest() {
        // TODO: test tierValueMinimum
    }

    /**
     * Test the property 'tierValueMaximum'
     */
    @Test
    public void tierValueMaximumTest() {
        // TODO: test tierValueMaximum
    }

    /**
     * Test the property 'calculationFrequency'
     */
    @Test
    public void calculationFrequencyTest() {
        // TODO: test calculationFrequency
    }

    /**
     * Test the property 'applicationFrequency'
     */
    @Test
    public void applicationFrequencyTest() {
        // TODO: test applicationFrequency
    }

    /**
     * Test the property 'depositInterestAppliedCoverage'
     */
    @Test
    public void depositInterestAppliedCoverageTest() {
        // TODO: test depositInterestAppliedCoverage
    }

    /**
     * Test the property 'fixedVariableInterestRateType'
     */
    @Test
    public void fixedVariableInterestRateTypeTest() {
        // TODO: test fixedVariableInterestRateType
    }

    /**
     * Test the property 'AER'
     */
    @Test
    public void AERTest() {
        // TODO: test AER
    }

    /**
     * Test the property 'bankInterestRateType'
     */
    @Test
    public void bankInterestRateTypeTest() {
        // TODO: test bankInterestRateType
    }

    /**
     * Test the property 'bankInterestRate'
     */
    @Test
    public void bankInterestRateTest() {
        // TODO: test bankInterestRate
    }

    /**
     * Test the property 'notes'
     */
    @Test
    public void notesTest() {
        // TODO: test notes
    }

    /**
     * Test the property 'otherBankInterestType'
     */
    @Test
    public void otherBankInterestTypeTest() {
        // TODO: test otherBankInterestType
    }

    /**
     * Test the property 'otherApplicationFrequency'
     */
    @Test
    public void otherApplicationFrequencyTest() {
        // TODO: test otherApplicationFrequency
    }

    /**
     * Test the property 'otherCalculationFrequency'
     */
    @Test
    public void otherCalculationFrequencyTest() {
        // TODO: test otherCalculationFrequency
    }

}
